---
name: SAS Viya Report Packages CI/CD

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: Force report package update
        type: boolean
        default: false
  # Comment out scheduled run since system is permanently down
  # schedule:
  #   # 10:30AM EST, Monday - Friday
  #   - cron: '30 14 * * 1-5'

env:
  LIGHT_UID: e12f78ec-aa6a-43ca-a03f-a997c123c939
  DARK_UID: 2aee9448-2522-46e2-a2a9-1998695ae58c

jobs:
  create_report_packages:
    name: Create Report Packages
    runs-on: self-hosted
    outputs:
      light-artifact-id: ${{ steps.create_package_light.outputs.artifact-id }}
      dark-artifact-id: ${{ steps.create_package_dark.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3
      - name: Light Theme
        id: create_package_light
        uses: ./.github/actions/create-report-package
        with:
          viya-endpoint: ${{ vars.SAS_SERVICES_ENDPOINT }}
          viya-auth-token: ${{ secrets.SAS_VIYA_CLI_AUTH_TOKEN }}
          report-uid: ${{ env.LIGHT_UID }}
          force-update: ${{ inputs.force_update }}
      - name: Dark Theme
        id: create_package_dark
        uses: ./.github/actions/create-report-package
        with:
          viya-endpoint: ${{ vars.SAS_SERVICES_ENDPOINT }}
          viya-auth-token: ${{ secrets.SAS_VIYA_CLI_AUTH_TOKEN }}
          report-uid: ${{ env.DARK_UID }}
          force-update: ${{ inputs.force_update }}

  commit_report_package:
    name: Commit Report Package
    needs: create_report_packages
    # Only run if we have an artifact
    if: needs.create_report_packages.outputs.light-artifact-id || needs.create_report_packages.outputs.dark-artifact-id
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Download report packages
        uses: actions/download-artifact@v4
        with:
          path: downloads
      - name: Stage light package
        if: needs.create_report_packages.outputs.light-artifact-id
        run: |
          unzip downloads/package-${{ env.LIGHT_UID }}/report.sasreportpkg.zip -d downloads/${{ env.LIGHT_UID }}
          rm -rf repo/public/reportPackages/${{ env.LIGHT_UID }}
          mv downloads/${{ env.LIGHT_UID }} repo/public/reportPackages
      - name: Stage dark package
        if: needs.create_report_packages.outputs.dark-artifact-id
        run: |
          unzip downloads/package-${{ env.DARK_UID }}/report.sasreportpkg.zip -d downloads/${{ env.DARK_UID }}
          rm -rf repo/public/reportPackages/${{ env.DARK_UID }}
          mv downloads/${{ env.DARK_UID }} repo/public/reportPackages
      - name: Create Pull Request
        run: |
          cd repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-report-package
          git add .
          git commit -m "feat: update report package"
          git push origin update-report-package
          gh pr create --title "Update report package" --body "Automated updated of the SAS Viya report package"
          gh pr merge --squash --auto --delete-branch
