name: SAS Viya Report Packages CI/CD

on:
  workflow_dispatch

jobs:
  create_report_package:
    name: Create Report Package
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CLI_CONTAINER_NAME }}
      env:
        SAS_SERVICES_ENDPOINT: ${{ vars.SAS_SERVICES_ENDPOINT }}
        SAS_VIYA_CLI_AUTH_TOKEN: ${{ secrets.SAS_VIYA_CLI_AUTH_TOKEN }}
        REPORT_UID: ${{ vars.REPORT_UID }}
    steps:
      - name: Install plugins
        run: HOME=/home/sas sas-admin plugins install --repo SAS reports
      - name: Login
        run: HOME=/home/sas sas-admin -k auth loginJwt -jwt $SAS_VIYA_CLI_AUTH_TOKEN
      - name: Create package
        run: |
          mkdir /home/sas/reportPackage
          HOME=/home/sas sas-admin -k reports build-package --id $REPORT_UID --output-location /home/sas/reportPackage --output-file report
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: reportPackage
          path: /home/sas/reportPackage
          if-no-files-found: error
          
  commit_report_package:
    name: Commit Report Package
    needs: create_report_package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: reportPackage
          path: downloads
      - name: Prepare commit
        run: |
          cd downloads
          unzip downloads/report.sasreportpkg.zip -d downloads/demo
          rm -rf repo/public/reportPackages/demo
          mv downloads/demo repo/public/reportPackages
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          path: repo
          branch: update-report-package
          commit-message: "feat: update report package"
          title: "update report package"
          body: "Automated updated of the SAS Viya report package"
          
