name: SAS Viya Report Packages CI/CD

on:
  workflow_dispatch

jobs:
  create_report_package:
    name: Create Report Package
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CLI_CONTAINER_NAME }}
      env:
        SAS_SERVICES_ENDPOINT: ${{ vars.SAS_SERVICES_ENDPOINT }}
        SAS_VIYA_CLI_AUTH_TOKEN: ${{ secrets.SAS_VIYA_CLI_AUTH_TOKEN }}
        REPORT_UID: ${{ vars.REPORT_UID }}
    steps:
      - name: Install Plugins
        run: HOME=/home/sas sas-admin plugins install --repo SAS reports
      - name: Login
        run: HOME=/home/sas sas-admin -k auth loginJwt -jwt $SAS_VIYA_CLI_AUTH_TOKEN
      - name: Create Package
        run: |
          HOME=/home/sas
          mkdir ~/reportPackages
          cd ~/reportPackages
          echo $(date) > date.txt
          sas-admin -k --verbose reports build-package --id $REPORT_UID --output-file report
      - run: pwd
      - run: ls -la /home/sas/reportPackages
